### PR TITLE
Add form exit warning popup

### LINKED ISSUE #64: Form exit warning popup
*User Story: As a developer, I would like to have a server action that can approve form submissions.*

### Description
For this story, we want to warn participants that their progress may not be saved if they leave the form. This will be important in motivating users to continue the form to completion. However, more importantly, it will avoid upsetting participants if their work on the form is not saved.

### PR DESCRIPTION
**Pull request by jacksonmowry**
# Description

Adds an event listener to watch for a page close, warning the user that their information will not be saved.
## Relevant issue(s)
Closes #64 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

### CODE REVIEW

**Review by cfisher36 — CHANGES_REQUESTED** [review]
Looks like the BeforeUnloadEvent doesn't block the "go back" browser action. I looked into it a little bit, and it seems that others are having a lot of the same issues with the new app router. As it exists, it seems that there are two options:
- ugly hack
- tracking form state in session storage and giving a warning on unload events from landing page

I think that we can add this to technical debt for now though. I'll make an item on the project board so that we know to revisit. For this story, it will be fine to just make the isDirty change.

Relevant resources:

```ts
// usePageUnloadGuardHook.ts

import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useEffect } from 'react';

// TODO: Implement this hook properly if we have any other option like router events
// or interceptors

const clickType = typeof document !== 'undefined' && document.ontouchstart ? 'touchstart' : 'click';

interface GuardEventListener {
  onBeforeUnload: () => boolean;
}

export default function usePageUnloadGuard() {
  const router = useRouter();

  const pathname = usePathname();
  const searchParams = useSearchParams();

  const listener: GuardEventListener = {
    onBeforeUnload: () => false,
  };

  const beforeUnloadHandler = (event: BeforeUnloadEvent) => {
    listener.onBeforeUnload() && event.preventDefault();
  };

  const clickHandler = (event: MouseEvent | TouchEvent) => {
    if ((event as MouseEvent).button || event.which !== 1) return;
    if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;

    const target = event.target as HTMLElement;
    if (target.tagName !== 'A') {
      return;
    }

    const newPath = target.getAttribute('href');
    if (newPath && newPath !== window.location.pathname && listener.onBeforeUnload()) {
      event.preventDefault();
      // NOTE: There is an option to show standard beforeunload dialog here by
      // actually assigning window.location.href to newPath. That will be more
      // consistent, but will cause full page reload in case of the user decides to
      // go back.
      // window.location.href = newPath; // This will show the standard dialog
      if (confirm('Your changes will not be saved if you leave the page.')) {
        router.push(newPath);
      }
    }
  };

  const popStateHandler = (event: PopStateEvent) => {
    if (event.state !== null) {
      return;
    }
    if (listener.onBeforeUnload() && confirm('Your changes will not be saved if you leave the page.')) {
      window.removeEventListener('popstate', popStateHandler);
      history.back();
      return;
    }
    // Returning to the fake history state
    history.go(1);
  };

  useEffect(() => {
    // Since 'popstate' fires at the end of the page swap, there is no option to
    // cancel it. So we're adding artificial state and in case we got there,
    // it means a user pressed back button.
    // TODO: Check if it is safe to add these to deps so the effect will re-run with pathname and params change
    history.pushState(null, '', pathname + searchParams.toString());
    window.addEventListener('beforeunload', beforeUnloadHandler);
    window.addEventListener('popstate', popStateHandler);
    window.document.addEventListener(clickType, clickHandler, { capture: true });
    return () => {
      window.removeEventListener('popstate', popStateHandler);
      window.removeEventListener('beforeunload', beforeUnloadHandler);
      window.document.removeEventListener(clickType, clickHandler, { capture: true });
    };
  });

  return listener;
}

// page.tsx

const listener = usePageUnloadGuard();
listener.onBeforeUnload = () => !!isDirty;
```

Links to Discussions:
- https://github.com/vercel/next.js/discussions/41934
- https://github.com/vercel/next.js/discussions/42016
- https://github.com/vercel/next.js/issues/2694

**Comment by jacksonmowry** [comment]
output

Is this the desired behavior? It shows me the warning when closing the tab or using the back button.

**Comment by cfisher36** [comment]
Thought I was going crazy for a second because yeah, that's how it should behave. However, the issue occurs when you are redirected to the form using the "Get Started!" button on the landing page. 

For example, it won't work if you start at http://localhost:3000/?id=6554b0860b05ad64d04e6a05 (which contains an active agency), click "Get Started!". and attempt to go back after populating the form.

**Review by cfisher36 — APPROVED** [review]
looks great :)

**Pull request merged**
